import Head from 'next/head'
import Banner from './components/Banner'

function HomePage() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Banner />
            <div style={{ height: 1000 }}></div>
        </>
    )
}

export default HomePage
